#spring.application.name=tickets

server:
  port: 8078
spring:
  application:
    name: tickets

  datasource:
    url: jdbc:postgresql://localhost:5432/pluralsight
    username: pluralsight
    password: pluralsight
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: never
